[book]
authors = ["Abdulla Abdurakhmanov"]
language = "en"
src = "src"
title = "BigQuery for Rust"
description = "Library provides a simple API for Google BigQuery based on the gRPC Storage Read/Write and v2 APIs"

[rust]
edition = "2021"

[build]
build-dir = "output"
create-missing = false

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/abdolence/bigquery-rs"
cname = "bigquery-rust.abdolence.dev"

[output.html.playground]
runnable = false
